'use strict';
(() => {
  const $ = (id) => document.getElementById(id);
  const $$ = (query, root = document) => [...root.querySelectorAll(query)];
  const state = {
    files: {a: [], b: [], audio: []}, cameras: [{id:'A',key:'a',label:'Camera A'},{id:'B',key:'b',label:'Camera B'}], framing: new Map(), shotOverrides: [], sourceFrame: null, selectedFrame: '', latestEdit: null, page: 'edit', waves: {}, metadata: new Map(), overrides: new Map(),
    config: null, jobId: null, pollTimer: null, busy: false, uploadBusy: false,
    reportKey: '', lastLog: '', previewUrls: {}, previewFiles: {},
    browser: {target: 'a', path: '', parent: null, entries: [], selected: new Set(), request: 0},
  };
  const draftState={key:'multicam-studio:last-project:v1',ready:false,offered:null,timer:null,signature:''};
  const setupState={data:null,firstRun:false,step:0,saving:false,loading:false,stopped:false};
  const natural = new Intl.Collator(undefined, {numeric: true, sensitivity: 'base'});
  // Paths may use / (macOS, Linux, Docker) or a backslash (Windows).
  const basename = (p) => String(p).split(/[\\/]/).pop() || p;
  const dirname = (p) => { const parent = String(p).replace(/[\\/][^\\/]+[\\/]?$/, ''); return /^[A-Za-z]:$/.test(parent) ? parent + '\\' : parent || '/'; };
  const mode = () => document.querySelector('[name="mode"]:checked').value;
  const number = (id) => Number($(id).value);
  function textEl(tag, text, className) { const el = document.createElement(tag); el.textContent = text; if(className) el.className = className; return el; }
  function showError(error) { $('error-banner').querySelector('span').textContent = error.message || String(error); $('error-banner').hidden = false; $('error-banner').scrollIntoView({behavior: 'smooth', block: 'nearest'}); }
  function toast(message) { $('toast').textContent = message; $('toast').hidden = false; clearTimeout(toast.timer); toast.timer = setTimeout(() => { $('toast').hidden = true; }, 4000); }
  function timecode(seconds, precision = 1) {
    if(!Number.isFinite(Number(seconds))) return '—';
    const sign = Number(seconds) < 0 ? '−' : ''; let n = Math.abs(Number(seconds));
    n = Math.round(n * 10 ** precision) / 10 ** precision;
    const h = Math.floor(n / 3600), m = Math.floor(n % 3600 / 60), s = (n % 60).toFixed(precision);
    return sign + (h ? `${h}:` : '') + String(m).padStart(2,'0') + ':' + s.padStart(precision ? 3+precision : 2,'0');
  }
  function bytes(value) { if(!Number.isFinite(Number(value))) return ''; const n = Number(value); return n >= 1e9 ? `${(n/1e9).toFixed(1)} GB` : n >= 1e6 ? `${(n/1e6).toFixed(1)} MB` : `${Math.max(1,Math.round(n/1e3))} KB`; }
  async function api(path, data) {
    const options = {headers: {'X-Multicam-Token': window.MULTICAM_TOKEN}};
    if(data !== undefined) { options.method = 'POST'; options.headers['Content-Type'] = 'application/json'; options.body = JSON.stringify(data); }
    const response = await fetch(path, options);
    let body; try {body = await response.json();} catch {throw new Error(`Server returned ${response.status}. Make sure Multicam Studio is still running.`);}
    if(!response.ok) throw new Error(body.error || body.message || `Request failed (${response.status})`);
    return body;
  }
  $('error-banner').querySelector('button').addEventListener('click', () => { $('error-banner').hidden = true; });

  function renderFiles(target) {
    const list = $(`files-${target}`); if(!list)return; list.replaceChildren();
    state.files[target].forEach((path, index) => {
      const row = textEl('div', '', 'file-row');
      const info = textEl('div', '', 'file-info'); info.title = path;
      info.append(textEl('div', basename(path), 'file-name'));
      const meta = state.metadata.get(path);
      let detail = meta ? (meta.error || [meta.duration != null ? timecode(meta.duration,0) : '', meta.width && meta.height ? `${meta.width} × ${meta.height}` : '', target !== 'audio' && meta.has_audio === false ? 'No camera audio · set manual offset' : ''].filter(Boolean).join(' · ')) : 'Reading file…';
      info.append(textEl('div', detail || 'File selected', 'file-meta' + (meta?.error ? ' error-text' : ''))); row.append(info);
      if(target !== 'audio' && state.files[target].length > 1) {
        [['↑', -1, 'Move part up'],['↓', 1, 'Move part down']].forEach(([symbol, step, label]) => {
          const button = textEl('button', symbol); button.type='button'; button.title=label; button.setAttribute('aria-label', `${label}: ${basename(path)}`); button.disabled=index+step<0 || index+step>=state.files[target].length;
          button.addEventListener('click', () => {const files = state.files[target]; [files[index],files[index+step]]=[files[index+step],files[index]]; renderFiles(target); renderOverrides(); }); row.append(button);
        });
      }
      if(target!=='audio'){const frame=textEl('button','▣');frame.type='button';frame.title='Set framing for this clip';frame.setAttribute('aria-label',`Set framing for ${basename(path)}`);frame.addEventListener('click',()=>{state.selectedFrame=path;updateFramePicker();loadSourceFrame();});row.append(frame);}
      const remove = textEl('button','×'); remove.type='button'; remove.title='Remove file'; remove.setAttribute('aria-label',`Remove ${basename(path)}`);
      remove.addEventListener('click', () => {state.files[target].splice(index,1); renderFiles(target); renderOverrides(); updateFramePicker(); updateCameraSelectors(); if(target!=='audio') {delete state.previewUrls[target]; renderPreviews();} }); row.append(remove); list.append(row);
    });
  }
  async function addFiles(target, paths) {
    const unique = [...new Set(paths)].filter(Boolean);
    if(target === 'audio') state.files.audio = unique.slice(0,1);
    else state.files[target] = [...new Set([...(state.files[target]||[]), ...unique])].sort(natural.compare);
    renderFiles(target); renderOverrides(); updateFramePicker(); updateCameraSelectors();scheduleAutosave();
    if(target !== 'audio') renderPreviews();
    const unprobed = unique.filter(p => !state.metadata.has(p));
    if(unprobed.length) {
      try { const result = await api('/api/probe', {paths: unprobed}); (result.files || []).forEach(file => state.metadata.set(file.path,file)); }
      catch(error) { unprobed.forEach(path=>state.metadata.set(path,{error:error.message})); showError(error); }
      renderFiles(target);
    }
  }
  function renderOverrides() {
    const host = $('sync-overrides'); host.replaceChildren();
    for(const camera of state.cameras) for(const path of state.files[camera.key]||[]) {
      const block = textEl('div','','sync-override'); block.append(textEl('h3',`${camera.id} · ${basename(path)}`));
      const grid = textEl('div','','grid-two'); const value = state.overrides.get(path) || {};
      for(const [key,label,placeholder] of [['offset','Start offset (seconds)','Auto'],['drift_ppm','Clock drift (ppm)','Auto']]) {
        const wrapper = textEl('label',label); const input=document.createElement('input'); input.type='number'; input.step=key==='offset'?'0.001':'0.1'; input.placeholder=placeholder; input.value=value[key] ?? '';
        input.addEventListener('input',()=>{const current=state.overrides.get(path)||{}; current[key]=input.value===''?null:Number(input.value); state.overrides.set(path,current);}); wrapper.append(input); grid.append(wrapper);
      } block.append(grid); host.append(block);
    }
    if(!host.childElementCount) host.append(textEl('p','Add camera files to set individual timing overrides.','help'));
  }

  async function openBrowser(target) {
    state.browser.target=target; state.browser.selected.clear(); const folder=isFolderTarget(target); const special=sourceField(target);
    $('browser-title').textContent=folder?(target==='setup-default-folder'?'Choose a recordings folder':'Choose an output folder'):target==='audio'?'Choose your audio bounce':special?'Choose a finished movie':`Choose ${state.cameras.find(c=>c.key===target)?.label||target} files`;
    $('browser-select').textContent=folder?'Use this folder':target==='audio'?'Use selected audio':special?'Use selected movie':'Add selected files';
    $('browser-error').hidden=true;$('new-folder-form').hidden=true;$('new-folder-button').hidden=!folder; $('file-dialog').showModal();
    const field=folder?outputField(target):special;const existing=field?($(field).value?(folder?$(field).value:dirname($(field).value)):''):state.files[target]?.[0]?dirname(state.files[target][0]):'';
    await browse(existing || state.browser.path || state.config?.default_folder || '/');
  }
  async function browse(path) {
    const request=++state.browser.request;
    $('browser-list').replaceChildren(textEl('div','Loading folder…','browser-message'));
    $('browser-select').disabled=true; $('new-folder-button').disabled=true; $('browser-error').hidden=true;
    try {
      const kind=isFolderTarget(state.browser.target)?'folder':state.browser.target==='audio'?'audio':'video';
      let response,candidate=path,attempts=0;while(true){try{response=await api(`/api/browse?path=${encodeURIComponent(candidate)}&kind=${kind}`);break;}catch(error){const parent=dirname(candidate);if(!isFolderTarget(state.browser.target)||parent===candidate||++attempts>24)throw error;candidate=parent;}}if(candidate!==path||response.fallback){$('browser-error').textContent=`That folder is unavailable. Showing its closest accessible parent: ${response.path}`;$('browser-error').hidden=false;}
      if(request!==state.browser.request) return;
      Object.assign(state.browser,{path:response.path,parent:response.parent,entries:response.entries||[]});
      $('browser-path').value=response.path; $('browser-up').disabled=!response.parent || response.parent===response.path;
      const roots=$('browser-roots'); roots.replaceChildren();
      (response.roots||state.config?.roots||[]).forEach(root=>{const button=textEl('button',basename(root)||root); button.type='button';button.title=root;button.addEventListener('click',()=>browse(root));roots.append(button);});
      renderBrowser();
    } catch(error) {if(request!==state.browser.request)return; $('browser-error').textContent=error.message;$('browser-error').hidden=false;$('browser-list').replaceChildren(textEl('div','Enter another folder path above.','browser-message'));}
  }
  function renderBrowser() {
    const host=$('browser-list');host.replaceChildren();const folderMode=isFolderTarget(state.browser.target);
    const entries=[...state.browser.entries].sort((a,b)=>Number(b.is_dir)-Number(a.is_dir)||natural.compare(a.name,b.name));
    entries.forEach(entry=>{
      const button=textEl('button','','browser-entry'+(state.browser.selected.has(entry.path)?' selected':''));button.type='button';button.title=entry.path;
      button.append(textEl('span',entry.is_dir?'▸':'','browser-entry-icon'));
      if(!entry.is_dir){const check=textEl('span',state.browser.selected.has(entry.path)?'✓':'','browser-entry-check');check.setAttribute('aria-hidden','true');button.append(check);button.setAttribute('aria-pressed',String(state.browser.selected.has(entry.path)));}
      button.append(textEl('span',entry.name,'browser-entry-name'),textEl('span',entry.is_dir?'Folder':bytes(entry.size),'browser-entry-size'));
      button.addEventListener('click',()=>{if(entry.is_dir){browse(entry.path);}else{if(state.browser.selected.has(entry.path))state.browser.selected.delete(entry.path);else{if(state.browser.target==='audio'||sourceField(state.browser.target))state.browser.selected.clear();state.browser.selected.add(entry.path);}renderBrowser();}});host.append(button);
    });
    if(!entries.length)host.append(textEl('div',folderMode?'No subfolders. You can use this folder.':'No matching files in this folder.','browser-message'));
    $('browser-selection').textContent=folderMode?state.browser.path:`${state.browser.selected.size} file${state.browser.selected.size===1?'':'s'} selected`;
    $('browser-select').disabled=!folderMode&&!state.browser.selected.size;$('new-folder-button').disabled=false;
  }
  $$('[data-browse]').forEach(button=>button.addEventListener('click',()=>openBrowser(button.dataset.browse)));
  renderCameraCards();
  $('browse-output').addEventListener('click',()=>openBrowser('output'));
  $('browser-close').addEventListener('click',()=>$('file-dialog').close());
  $('browser-up').addEventListener('click',()=>browse(state.browser.parent));
  $('browser-path-form').addEventListener('submit',event=>{event.preventDefault();browse($('browser-path').value);});
  $('browser-select').addEventListener('click',()=>{const target=state.browser.target;const paths=[...state.browser.selected];if(isFolderTarget(target))$(outputField(target)).value=state.browser.path;else if(sourceField(target))$(sourceField(target)).value=paths[0]||'';else addFiles(target,paths);$('file-dialog').close();scheduleAutosave();});

  function uploadFile(file,index,total) {
    return new Promise((resolve,reject)=>{
      const xhr=new XMLHttpRequest();xhr.open('POST',`/api/upload?name=${encodeURIComponent(file.name)}`);xhr.setRequestHeader('X-Multicam-Token',window.MULTICAM_TOKEN);xhr.setRequestHeader('Content-Type','application/octet-stream');
      xhr.upload.addEventListener('progress',event=>{const progress=event.lengthComputable?` · ${Math.round(event.loaded/event.total*100)}%`:'';$('upload-status').textContent=`Copying ${index}/${total}: ${file.name}${progress}`;});
      xhr.addEventListener('load',()=>{let result;try{result=JSON.parse(xhr.responseText);}catch{return reject(new Error('Upload failed: the local server returned an invalid response.'));}if(xhr.status<200||xhr.status>=300)return reject(new Error(result.error||'Upload failed.'));resolve(result.path);});
      xhr.addEventListener('error',()=>reject(new Error('Could not upload the file. Check the local server and available disk space.')));xhr.addEventListener('abort',()=>reject(new Error('Upload cancelled.')));xhr.send(file);
    });
  }
  async function uploadFiles(target,files) {
    if(state.uploadBusy){toast('Wait for the current file copy to finish.');return;}if(!files.length)return;
    if(target==='audio')files=files.slice(0,1);state.uploadBusy=true;setJobButtons();$('upload-status').hidden=false;
    try {for(let i=0;i<files.length;i++){const path=await uploadFile(files[i],i+1,files.length);await addFiles(target,[path]);}$('upload-status').textContent=`${files.length} file${files.length===1?'':'s'} copied. Ready to use.`;}
    catch(error){$('upload-status').textContent='File copy stopped.';showError(error);}finally{state.uploadBusy=false;setJobButtons();}
  }
  $$('[data-upload]').forEach(button=>button.addEventListener('click',()=>$(`upload-${button.dataset.upload}`).click()));
  for(const target of ['audio']) {
    $(`upload-${target}`).addEventListener('change',event=>{uploadFiles(target,[...event.target.files]);event.target.value='';});
    const card=target==='audio'?document.querySelector('.audio-card'):$(`source-${target}`);
    card.addEventListener('dragover',event=>{event.preventDefault();card.classList.add('dragover');});card.addEventListener('dragleave',()=>card.classList.remove('dragover'));
    card.addEventListener('drop',event=>{event.preventDefault();card.classList.remove('dragover');uploadFiles(target,[...event.dataTransfer.files]);});
  }

  function setTab(name) {$$('[data-tab]').forEach(button=>button.setAttribute('aria-selected',String(button.dataset.tab===name)));$('framing-view').hidden=name!=='framing';$('output-view').hidden=name!=='output';}
  $$('[data-tab]').forEach(button=>button.addEventListener('click',()=>setTab(button.dataset.tab)));
  function cropValues(angle) {return [number(`${angle}-x`),number(`${angle}-y`)];}
  function renderPreviews() {
    const host=$('crop-previews');host.replaceChildren();
    const entries=Object.entries(state.previewUrls).filter(([,url])=>url);
    host.hidden=!entries.length;$('preview-empty').hidden=entries.length>0||!!state.sourceFrame;
    for(const [key,url]of entries){const block=textEl('div','','crop-preview'),figure=document.createElement('figure'),img=document.createElement('img');img.src=url;img.alt='Output framing preview';const caption=textEl('figcaption',basename(state.previewFiles[key]||state.selectedFrame));const link=textEl('a','Full size ↗');link.href=url;link.target='_blank';link.rel='noopener';caption.append(link);figure.append(img,caption);block.append(figure);host.append(block);}
  }
  function updateFormat() {
    const vertical=mode()==='vertical';$('format-help').textContent=vertical?'Portrait output at 2160 × 3840. Each clip keeps its chosen fit or crop treatment.':'Landscape output at 3840 × 2160. Each clip keeps its chosen fit or crop treatment.';drawSourceFrame();
    $('format-summary').textContent=`4K · ${vertical?'9:16':'16:9'} · ${$('fps').value} FPS`;
    if(['multicam_cut.mp4','multicam_cut_vertical.mp4'].includes($('output-name').value))$('output-name').value=vertical?'multicam_cut_vertical.mp4':'multicam_cut.mp4';
    if(Object.keys(state.previewUrls).length)$('preview-note').textContent='Settings changed · regenerate crop previews';
  }
  $$('[name="mode"]').forEach(input=>input.addEventListener('change',updateFormat));$('fps').addEventListener('change',updateFormat);
  for(const id of ['a-x','a-y','b-x','b-y'])$(id).addEventListener('input',()=>{$('preview-note').textContent='Crop changed · regenerate to check framing';});
  function updateRole() {const main=$('main-camera').value;for(const camera of state.cameras){const role=$(`role-${camera.key}`);if(role)role.textContent=main===camera.id?'MAIN':'CUTAWAY';}$('share-value').textContent=`${Math.round(number('main-share')*100)}%`;}
  $('main-camera').addEventListener('change',updateRole);$('main-share').addEventListener('input',updateRole);

  function parseTime(value) {
    const clean=String(value).trim();if(!clean)throw new Error('Empty time value.');if(!/^\d+(?:\.\d+)?(?::\d+(?:\.\d+)?){0,2}$/.test(clean))throw new Error(`Invalid time “${clean}”. Use seconds, MM:SS or HH:MM:SS.`);
    const pieces=clean.split(':').map(Number);if(pieces.length>1&&pieces.slice(1).some(n=>n>=60))throw new Error(`Invalid time “${clean}”: minutes and seconds must be less than 60.`);
    return pieces.reduce((acc,n)=>acc*60+n,0);
  }
  function parseRanges(id,label) {return $(id).value.split(/[,;\n]+/).map(x=>x.trim()).filter(Boolean).map(line=>{const parts=line.split(/\s*[-–—]\s*/);if(parts.length!==2)throw new Error(`${label}: use a start–end range, such as 01:20–01:45.`);const result=parts.map(parseTime);if(result[1]<=result[0])throw new Error(`${label}: the end must come after the start.`);return result;});}
  function collectConfig(planOnly=false,validate=true) {
    if(validate&&!$('edit-form').reportValidity())throw new Error('Check the highlighted settings.');
    if(validate&&(!state.cameras.length||state.cameras.some(c=>!state.files[c.key]?.length)||!state.files.audio.length))throw new Error('Choose at least one recording for each camera and an audio bounce.');
    const config={cameras:state.cameras.map(c=>({id:c.id,label:c.label,clips:(state.files[c.key]||[]).map(path=>({path,framing:frameFor(path)}))})),shot_overrides:state.shotOverrides.map(o=>({...o})),audio:state.files.audio[0]||'',output_dir:$('output-dir').value.trim(),output_name:$('output-name').value.trim(),mode:mode(),main_camera:$('main-camera').value,main_share:number('main-share'),seed:number('seed'),fps:number('fps'),cut_scale:number('cut-scale'),a_center:cropValues('a'),b_center:cropValues('b'),auto_sections:$('auto-sections').checked,drift:$('drift').checked,crf:number('crf'),preset:$('preset').value,overwrite:$('overwrite').checked,plan_only:planOnly};
    for(const [prefix,key] of [['main','main_hold'],['cutaway','cutaway_hold'],['drop','drop_hold'],['breakdown','breakdown_hold']]){const pair=[number(`${prefix}-min`),number(`${prefix}-max`)];if(pair.some(n=>!Number.isFinite(n)||n<=0)||pair[0]>pair[1])throw new Error(`Check the ${prefix} shot range: use positive values with minimum ≤ maximum.`);config[key]=pair;}
    config.drops=parseRanges('drops','Drop markers');config.breakdowns=parseRanges('breakdowns','Breakdown markers');config.activities=$('activities').value.split(/[,;\n]+/).map(s=>s.trim()).filter(Boolean).map(parseTime);
    config.overrides=state.cameras.flatMap(c=>state.files[c.key]||[]).map(path=>({path,offset:state.overrides.get(path)?.offset ?? null,drift_ppm:state.overrides.get(path)?.drift_ppm ?? null})).filter(o=>o.offset!==null||o.drift_ppm!==null);
    if(validate&&/[/\\]/.test(config.output_name))throw new Error('Output filename must not contain a folder path. Set the folder separately.');
    return config;
  }
  function applyConfig(config) {
    const inputMap={output_dir:'output-dir',output_name:'output-name',main_camera:'main-camera',main_share:'main-share',seed:'seed',fps:'fps',cut_scale:'cut-scale',crf:'crf',preset:'preset'};
    Object.entries(inputMap).forEach(([key,id])=>{if(config[key]!=null)$(id).value=config[key];});
    if(config.mode){const radio=document.querySelector(`[name="mode"][value="${config.mode==='vertical'?'vertical':'horizontal'}"]`);radio.checked=true;}
    for(const [key,id]of [['auto_sections','auto-sections'],['drift','drift'],['overwrite','overwrite']])if(config[key]!=null)$(id).checked=!!config[key];
    for(const angle of ['a','b']){const values=config[`${angle}_center`];if(values?.length===2){$(`${angle}-x`).value=values[0];$(`${angle}-y`).value=values[1];}}
    for(const [key,prefix]of [['main_hold','main'],['cutaway_hold','cutaway'],['drop_hold','drop'],['breakdown_hold','breakdown']])if(config[key]?.length===2){$(`${prefix}-min`).value=config[key][0];$(`${prefix}-max`).value=config[key][1];}
    for(const key of ['drops','breakdowns'])if(Array.isArray(config[key]))$(key).value=config[key].map(pair=>`${timecode(pair[0],3)}–${timecode(pair[1],3)}`).join('\n');
    if(Array.isArray(config.activities))$('activities').value=config.activities.map(n=>timecode(n,3)).join(', ');
    state.overrides=new Map((config.overrides||[]).map(o=>[o.path,{offset:o.offset??null,drift_ppm:o.drift_ppm??null}]));
    state.files={audio:[]};state.framing=new Map();state.previewUrls={};state.previewFiles={};state.sourceFrame=null;state.selectedFrame='';const cameras=config.cameras||[{id:'A',label:'Camera A',clips:(config.cam_a||[]).map(path=>({path,framing:{mode:'crop',center:config.a_center||[.5,.5],zoom:1}}))},{id:'B',label:'Camera B',clips:(config.cam_b||[]).map(path=>({path,framing:{mode:'crop',center:config.b_center||[.5,.72],zoom:1}}))}];state.cameras=cameras.map((c,i)=>({id:c.id,key:'camera'+i,label:c.label||c.id}));for(let i=0;i<cameras.length;i++){state.files[state.cameras[i].key]=[];for(const clip of cameras[i].clips||[])state.framing.set(clip.path,clip.framing||{mode:'fit',center:[.5,.5],zoom:1});}renderCameraCards();for(let i=0;i<cameras.length;i++)addFiles(state.cameras[i].key,(cameras[i].clips||[]).map(c=>c.path));addFiles('audio',config.audio?[config.audio]:[]);state.shotOverrides=config.shot_overrides||[];renderShotOverrides();updateCameraSelectors();if(config.main_camera)$('main-camera').value=config.main_camera;renderOverrides();updateRole();updateFormat();
  }
  $('save-settings').addEventListener('click',()=>{try{const config=collectConfig(false,false);const blob=new Blob([JSON.stringify({version:1,...config},null,2)],{type:'application/json'});const link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download='multicam-setup.json';link.click();setTimeout(()=>URL.revokeObjectURL(link.href),1000);toast('Setup saved. It includes file paths and edit settings.');}catch(error){showError(error);}});
  $('load-settings').addEventListener('click',()=>$('settings-file').click());
  $('settings-file').addEventListener('change',async event=>{const file=event.target.files[0];event.target.value='';if(!file)return;try{const config=JSON.parse(await file.text());if(!config||typeof config!=='object'||(!Array.isArray(config.cameras)&&(!Array.isArray(config.cam_a)||!Array.isArray(config.cam_b))))throw new Error('Choose a Multicam Studio setup JSON file.');applyConfig(config);toast('Setup loaded. Check that the selected files are still available.');}catch(error){showError(error);}});

  function setJobButtons() {const disabled=state.busy||state.uploadBusy||state.config?.can_render===false;$('plan-button').disabled=disabled;$('render-button').disabled=disabled;$('cancel-button').hidden=!state.busy;for(const id of ['export-highlight','preview-effects','export-effects'])$(id).disabled=disabled;}
  async function startJob(planOnly) {
    if(state.busy||state.uploadBusy)return;
    try {
      const config=collectConfig(planOnly);state.activeKind='edit';$('error-banner').hidden=true;state.busy=true;setJobButtons();$('workspace-title').textContent=planOnly?'Building your edit plan.':'Bringing your set together.';
      const job=await api('/api/jobs',config);state.jobId=job.id;state.reportKey='';state.lastLog='';$('job-idle').hidden=true;$('job-progress').hidden=false;$('job-logs').textContent='Job queued…';$('job-stage').textContent='Queued';$('progress-value').textContent='';$('progress-fill').style.width='0';$('results').hidden=true;
      $('job-panel').scrollIntoView({behavior:'smooth',block:'nearest'});pollJob();
    } catch(error){state.busy=false;setJobButtons();showError(error);}
  }
  $('edit-form').addEventListener('submit',event=>{event.preventDefault();startJob(false);});$('plan-button').addEventListener('click',()=>startJob(true));
  $('cancel-button').addEventListener('click',async()=>{if(!state.jobId)return;$('cancel-button').disabled=true;$('cancel-button').textContent='Cancelling…';try{await api(`/api/jobs/${encodeURIComponent(state.jobId)}/cancel`,{});pollJob();}catch(error){showError(error);$('cancel-button').disabled=false;$('cancel-button').textContent='Cancel job';}});
  async function pollJob() {
    clearTimeout(state.pollTimer);if(!state.jobId)return;
    try{const requestedJob=state.jobId;const job=await api(`/api/jobs/${encodeURIComponent(requestedJob)}`);if(state.jobId!==requestedJob)return;renderJob(job);if(['queued','running'].includes(job.status))state.pollTimer=setTimeout(pollJob,1000);}
    catch(error){$('job-stage').textContent='Connection interrupted · trying again…';$('progress-value').textContent='';state.pollTimer=setTimeout(pollJob,3000);if(!state.busy)showError(error);}
  }
  function renderJob(job) {
    state.activeKind=job.kind||state.activeKind||'edit';updateToolProgress(job);
    const active=['queued','running'].includes(job.status);state.busy=active;setJobButtons();
    $('job-idle').hidden=true;$('job-progress').hidden=false;$('status-pill').textContent=String(job.status||'ready').toUpperCase();$('status-pill').dataset.status=job.status;
    const stage=job.stage||({completed:job.report?.status==='planned'?'Preview plan ready':'Render complete',failed:'Job failed',cancelled:'Job cancelled',queued:'Queued',running:'Processing…'}[job.status]);$('job-stage').textContent=stage;
    const progress=job.progress;const numeric=typeof progress==='number'&&Number.isFinite(progress);$('progress-value').textContent=numeric?`${Math.round(progress)}%`:active?'Working…':'';$('progress-fill').style.width=numeric?`${Math.max(0,Math.min(100,progress))}%`:job.status==='completed'?'100%':'0';document.querySelector('.progress-track').classList.toggle('indeterminate',active&&!numeric);
    const logs=(job.logs||[]).join('\n');if(logs!==state.lastLog){const log=$('job-logs');const atBottom=log.scrollHeight-log.scrollTop-log.clientHeight<40;log.textContent=logs||'Waiting for processing messages…';if(atBottom||!state.lastLog)log.scrollTop=log.scrollHeight;state.lastLog=logs;}
    if(!active){$('cancel-button').disabled=false;$('cancel-button').textContent='Cancel job';$('workspace-title').textContent=job.status==='completed'?(job.report?.status==='planned'?'Your edit is mapped out.':'Your set. Ready to share.'):job.status==='cancelled'?'Session cancelled.':'The edit needs attention.';}
    if(job.error){$('error-banner').querySelector('span').textContent=job.error;$('error-banner').hidden=false;}
    if(job.report){const reportKey=JSON.stringify([job.id,job.status,job.report.status,job.artifacts]);if(reportKey!==state.reportKey){state.reportKey=reportKey;if((job.kind||state.activeKind)==='edit'){renderReport(job.report,job.artifacts||[]);}else renderToolResult(job);}}
  }
  function renderReport(report,artifacts) {
    $('results').hidden=false;const stats=report.stats||{},duration=Number(report.duration_seconds)||0,shots=report.shots||[];
    $('result-mode').textContent=`${report.width||''} × ${report.height||''} · ${report.status==='rendered'?'RENDERED':'PLAN'}`;
    const statHost=$('stats');statHost.replaceChildren();
    for(const [value,label] of [[timecode(duration,0),'Total duration'],[String(stats.cut_count??Math.max(0,shots.length-1)),'Straight cuts'],[`${Math.round(Number(stats.main_share||0)*100)}%`,'Main screen time'],[`${Number(stats.average_cut_seconds||0).toFixed(1)}s`,'Average shot']]){const cell=textEl('div','','stat');cell.append(textEl('strong',value),textEl('span',label));statHost.append(cell);}
    renderTimelineKey(report);$('timeline-duration').textContent=timecode(duration,0);$('black-key').hidden=!Number(stats.black_seconds);const timeline=$('shot-timeline');timeline.replaceChildren();const shotRows=$('shots-table');shotRows.replaceChildren();
    shots.forEach((shot,index)=>{
      const start=Number(shot.start_seconds)||0,end=Number(shot.end_seconds)||0;const button=textEl('button','');button.type='button';button.dataset.angle=shot.angle;button.style.background=cameraColor(shot.angle);button.style.flexBasis=`${duration?(end-start)/duration*100:0}%`;button.style.flexGrow=String(Math.max(.0001,end-start));const hint=`${timecode(start)} → ${timecode(end)} · ${shot.angle==='BLACK'?'No footage':`Camera ${shot.angle}`} · ${basename(shot.source_path||'')} · ${shot.reason||''}`;button.title=hint;button.setAttribute('aria-label',`Shot ${index+1}: ${hint}`);button.addEventListener('click',()=>{$('timeline-hint').textContent=hint;if($('output-video').getAttribute('src')){$('output-video').currentTime=start;setTab('output');}});timeline.append(button);
      const row=document.createElement('tr');[shot.index??index+1,timecode(start),timecode(end),shot.angle,basename(shot.source_path||'—'),shot.source_in_seconds==null?'—':timecode(shot.source_in_seconds),shot.reason||'—'].forEach(value=>row.append(textEl('td',String(value))));shotRows.append(row);
    });
    if(Number(stats.black_seconds)>0)$('timeline-hint').textContent=`${Number(stats.black_seconds).toFixed(1)} seconds have no camera coverage. Check the cut list before rendering.`;else $('timeline-hint').textContent='Select a shot to see its timing'+(report.status==='rendered'?' and seek the finished video.':'.');
    const syncHost=$('sync-table');syncHost.replaceChildren();(report.sync||[]).forEach(sync=>{const row=document.createElement('tr');const offset=Number(sync.offset_seconds);const drift=sync.drift_ppm!=null?Number(sync.drift_ppm):(Number(sync.rate)-1)*1e6;[`${sync.angle} · ${sync.filename||basename(sync.source_path)}`,`${offset>=0?'+':''}${offset.toFixed(3)} s`,`${drift>=0?'+':''}${drift.toFixed(1)} ppm`,`${timecode(sync.coverage_start_seconds,0)}–${timecode(sync.coverage_end_seconds,0)}`].forEach(value=>row.append(textEl('td',value)));syncHost.append(row);});
    const downloads=$('downloads');downloads.replaceChildren();artifacts.filter(a=>a.kind!=='image').forEach(artifact=>{const link=textEl('a',`${artifact.kind==='video'?'↓ Video':artifact.kind==='cut_list'?'↓ Cut list':artifact.kind==='report'?'↓ Edit report':artifact.kind==='log'?'↓ Log':`↓ ${artifact.name}`}`);link.href=artifact.url;link.download=artifact.name;link.title=artifact.name;downloads.append(link);});
    const video=artifacts.find(a=>a.kind==='video');if(report.outputs?.video){state.latestEdit=report.outputs.video;$('highlight-source').value=state.latestEdit;if(!$('effects-source').value)$('effects-source').value=state.latestEdit;}
    if(video){$('output-video').src=video.url;$('output-video').hidden=false;document.querySelector('.empty-output').hidden=true;setTab('output');}else{$('output-video').removeAttribute('src');$('output-video').load();$('output-video').hidden=true;document.querySelector('.empty-output').hidden=false;}
    const previews=report.outputs?.previews||[];for(const preview of previews){const artifact=artifacts.find(a=>a.kind==='image'&&(a.name===basename(preview.path)||a.path===preview.path));const angle=String(preview.angle);if(artifact&&!state.previewUrls[angle]){state.previewUrls[angle]=artifact.url;state.previewFiles[angle]=preview.source_path;}}
    renderPreviews();
  }
  async function initialize() {
    renderCameraCards();renderOverrides();updateFormat();
    try {
      state.config=await api('/api/config');if(state.config.server_mode)for(const row of $$('.quit-row'))row.hidden=true;$('output-dir').value=state.config.default_output||state.config.default_folder||'';for(const id of ['highlight-output','effects-output'])$(id).value=$('output-dir').value;
      const dependencies=state.config.dependencies||{};const missing=Object.entries(dependencies).filter(([,value])=>!value||(typeof value==='object'&&value.available===false)).map(([key])=>key);
      if(missing.length){$('dependency-warning').textContent=`Setup needed: ${missing.join(', ')}. Open Settings to check the editing tools before rendering.`;$('dependency-warning').hidden=false;}
      const result=await api('/api/jobs');const jobs=result.jobs||[];const previousEdit=jobs.find(j=>(j.kind==='edit'||!j.kind)&&j.config?.audio);if(previousEdit?.config)applyConfig(previousEdit.config);const exportedEdit=jobs.find(j=>(j.kind==='edit'||!j.kind)&&j.report?.outputs?.video);if(exportedEdit){state.latestEdit=exportedEdit.report.outputs.video;$('highlight-source').value=state.latestEdit;$('effects-source').value=state.latestEdit;}const active=jobs.find(job=>['queued','running'].includes(job.status));const latest=active||jobs[0];
      if(latest){state.jobId=latest.id;const job=await api(`/api/jobs/${encodeURIComponent(latest.id)}`);if(job.config&&(job.kind==='edit'||!job.kind))applyConfig(job.config);renderJob(job);if(active)state.pollTimer=setTimeout(pollJob,1000);}
    }catch(error){showError(error);}
    finally{draftState.ready=true;offerLocalDraft();if(state.config?.setup_completed===false)openSetup(true);}
  }
  function isFolderTarget(target){return ['output','highlight-output','effects-output','setup-default-folder','setup-default-output'].includes(target);}
  function outputField(target){return target==='output'?'output-dir':target;}
  function sourceField(target){return target==='highlight'?'highlight-source':target==='effects'?'effects-source':null;}
  function cameraColor(id){const index=state.cameras.findIndex(c=>c.id===id);return id==='BLACK'?'#606757':['#e6b774','#8dcccf','#bbabde','#b9cf8e','#e69eae','#89b3e7'][Math.max(0,index)%6];}
  function frameFor(path){const saved=state.framing.get(path)||{};return {mode:saved.mode||'fit',center:Array.isArray(saved.center)?[Number(saved.center[0]),Number(saved.center[1])]:[.5,.5],zoom:Number(saved.zoom)||1};}
  function renderCameraCards(){
    const host=$('camera-cards');host.replaceChildren();
    state.cameras.forEach((camera,index)=>{
      const card=textEl('div','','source-card');card.id=`source-${camera.key}`;const heading=textEl('div','','source-heading');const badge=textEl('span',camera.id,'angle-badge');badge.style.color=cameraColor(camera.id);badge.style.borderColor=cameraColor(camera.id)+'88';const name=document.createElement('input');name.className='camera-name';name.value=camera.label;name.setAttribute('aria-label',`Name for camera ${camera.id}`);name.maxLength=100;name.addEventListener('change',()=>{camera.label=name.value.trim()||camera.id;updateCameraSelectors();updateFramePicker();});const role=textEl('span',camera.id===$('main-camera').value?'MAIN':'CUTAWAY','role-badge');role.id=`role-${camera.key}`;heading.append(badge,name,role);
      if(state.cameras.length>1){const remove=textEl('button','×','icon-button');remove.type='button';remove.setAttribute('aria-label',`Remove ${camera.label}`);remove.addEventListener('click',()=>{state.cameras=state.cameras.filter(c=>c!==camera);delete state.files[camera.key];state.shotOverrides=state.shotOverrides.filter(o=>o.camera_id!==camera.id);renderCameraCards();renderOverrides();renderShotOverrides();updateFramePicker();});heading.append(remove);}
      const files=textEl('div','','file-list');files.id=`files-${camera.key}`;const actions=textEl('div','','source-actions');const browseButton=textEl('button','Browse files','small');browseButton.type='button';browseButton.addEventListener('click',()=>openBrowser(camera.key));const uploadButton=textEl('button','Upload files','small quiet');uploadButton.type='button';const input=document.createElement('input');input.type='file';input.accept='.mov,.mp4';input.multiple=true;input.hidden=true;uploadButton.addEventListener('click',()=>input.click());input.addEventListener('change',()=>{uploadFiles(camera.key,[...input.files]);input.value='';});actions.append(browseButton,uploadButton,input);card.append(heading,files,actions);host.append(card);renderFiles(camera.key);
      card.addEventListener('dragover',event=>{event.preventDefault();card.classList.add('dragover');});card.addEventListener('dragleave',()=>card.classList.remove('dragover'));card.addEventListener('drop',event=>{event.preventDefault();card.classList.remove('dragover');uploadFiles(camera.key,[...event.dataTransfer.files]);});
    });updateCameraSelectors();updateFramePicker();
  }
  $('add-camera').addEventListener('click',()=>{let count=state.cameras.length+1,id=count<=26?String.fromCharCode(64+count):`Cam${count}`;while(state.cameras.some(c=>c.id===id)){count++;id=`Cam${count}`;}const key=`camera_${Date.now()}`;state.cameras.push({id,key,label:`Camera ${id}`});state.files[key]=[];renderCameraCards();});
  function updateCameraSelectors(){for(const id of ['main-camera','override-camera']){const select=$(id),previous=select.value;select.replaceChildren();state.cameras.forEach(c=>{const option=textEl('option',`${c.id} · ${c.label}`);option.value=c.id;select.append(option);});if(state.cameras.some(c=>c.id===previous))select.value=previous;}updateOverrideParts();updateRole();}
  function updateOverrideParts(){const select=$('override-part'),previous=select.value;select.replaceChildren(textEl('option','Any available part'));select.firstElementChild.value='';const camera=state.cameras.find(c=>c.id===$('override-camera').value);for(const path of state.files[camera?.key]||[]){const option=textEl('option',basename(path));option.value=path;select.append(option);}if([...select.options].some(o=>o.value===previous))select.value=previous;}
  $('override-camera').addEventListener('change',updateOverrideParts);
  function updateFramePicker(){const select=$('frame-part');const paths=state.cameras.flatMap(c=>(state.files[c.key]||[]).map(path=>({path,c})));if(!paths.some(p=>p.path===state.selectedFrame))state.selectedFrame=paths[0]?.path||'';select.replaceChildren();for(const {path,c}of paths){const option=textEl('option',`${c.id} · ${basename(path)}`);option.value=path;select.append(option);}if(!paths.length){const option=textEl('option','Add a camera recording');option.value='';select.append(option);}select.value=state.selectedFrame;loadFramingControls();}
  function loadFramingControls(){const f=frameFor(state.selectedFrame);$('frame-mode').value=f.mode;$('frame-x').value=f.center[0];$('frame-y').value=f.center[1];$('frame-zoom').value=f.zoom;$('frame-zoom-value').textContent=Number(f.zoom).toFixed(2)+'×';const fit=f.mode==='fit';for(const id of ['frame-x','frame-y','frame-zoom'])$(id).disabled=fit;drawSourceFrame();}
  function saveFramingControls(){if(!state.selectedFrame)return;const framing={mode:$('frame-mode').value,center:[Math.min(1,Math.max(0,number('frame-x'))),Math.min(1,Math.max(0,number('frame-y')))],zoom:number('frame-zoom')};state.framing.set(state.selectedFrame,framing);loadFramingControls();$('preview-note').textContent='Framing saved · preview again to check output';}
  $('frame-part').addEventListener('change',()=>{state.selectedFrame=$('frame-part').value;state.sourceFrame=null;loadFramingControls();loadSourceFrame();});for(const id of ['frame-mode','frame-x','frame-y','frame-zoom'])$(id).addEventListener('input',saveFramingControls);
  async function loadSourceFrame(){if(!state.selectedFrame){showError('Add a camera recording first.');return;}const button=$('load-source-frame');button.disabled=true;button.textContent='Loading…';try{const path=state.selectedFrame;const result=await api('/api/source-frame',{path,time:number('frame-time')});const img=new Image();await new Promise((resolve,reject)=>{img.onload=resolve;img.onerror=()=>reject(new Error('Could not load the source frame.'));img.src=result.url;});if(state.selectedFrame!==path)return;state.sourceFrame={image:img,path,width:result.width,height:result.height};$('source-editor').hidden=false;$('preview-empty').hidden=true;$('source-editor-name').textContent=basename(path);drawSourceFrame();setTab('framing');}catch(error){showError(error);}finally{button.disabled=false;button.textContent='Load source frame';}}
  $('load-source-frame').addEventListener('click',loadSourceFrame);
  function cropRectangle(width,height,f){const ratio=mode()==='vertical'?9/16:16/9;let w=Math.min(width,height*ratio)/f.zoom,h=w/ratio;return {x:Math.min(width-w,Math.max(0,f.center[0]*width-w/2)),y:Math.min(height-h,Math.max(0,f.center[1]*height-h/2)),width:w,height:h};}
  function drawSourceFrame(){const frame=state.sourceFrame;if(!frame||frame.path!==state.selectedFrame){$('source-editor').hidden=true;return;}$('source-editor').hidden=false;const canvas=$('source-canvas'),ctx=canvas.getContext('2d');canvas.width=frame.width;canvas.height=frame.height;ctx.drawImage(frame.image,0,0,frame.width,frame.height);const f=frameFor(frame.path);$('source-editor-hint').textContent=f.mode==='fit'?'Full picture · bars added as needed':'Drag the box · arrow keys for fine movement';if(f.mode==='crop'){const r=cropRectangle(frame.width,frame.height,f);ctx.fillStyle='#050806a6';ctx.fillRect(0,0,frame.width,r.y);ctx.fillRect(0,r.y+r.height,frame.width,frame.height-r.y-r.height);ctx.fillRect(0,r.y,r.x,r.height);ctx.fillRect(r.x+r.width,r.y,frame.width-r.x-r.width,r.height);ctx.strokeStyle='#e7f1c8';ctx.lineWidth=Math.max(2,frame.width/500);ctx.strokeRect(r.x,r.y,r.width,r.height);ctx.strokeStyle='#e7f1c85e';ctx.lineWidth=1;for(const fraction of [1/3,2/3]){ctx.beginPath();ctx.moveTo(r.x+r.width*fraction,r.y);ctx.lineTo(r.x+r.width*fraction,r.y+r.height);ctx.moveTo(r.x,r.y+r.height*fraction);ctx.lineTo(r.x+r.width,r.y+r.height*fraction);ctx.stroke();}}}
  let cropDrag=null;const sourceCanvas=$('source-canvas');sourceCanvas.addEventListener('pointerdown',event=>{if(!state.sourceFrame||frameFor(state.selectedFrame).mode!=='crop')return;sourceCanvas.setPointerCapture(event.pointerId);cropDrag={x:event.clientX,y:event.clientY,center:[...frameFor(state.selectedFrame).center]};});sourceCanvas.addEventListener('pointermove',event=>{if(!cropDrag)return;const rect=sourceCanvas.getBoundingClientRect();const f=frameFor(state.selectedFrame),bounds=cropRectangle(1,state.sourceFrame.height/state.sourceFrame.width,{...f,center:[.5,.5]});const halfX=bounds.width/2,halfY=bounds.height/(state.sourceFrame.height/state.sourceFrame.width)/2;f.center=[Math.max(halfX,Math.min(1-halfX,cropDrag.center[0]+(event.clientX-cropDrag.x)/rect.width)),Math.max(halfY,Math.min(1-halfY,cropDrag.center[1]+(event.clientY-cropDrag.y)/rect.height))];state.framing.set(state.selectedFrame,f);loadFramingControls();});sourceCanvas.addEventListener('pointerup',()=>{cropDrag=null;});sourceCanvas.addEventListener('pointercancel',()=>{cropDrag=null;});sourceCanvas.addEventListener('keydown',event=>{if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(event.key)||!state.selectedFrame||frameFor(state.selectedFrame).mode!=='crop')return;event.preventDefault();const f=frameFor(state.selectedFrame),step=event.shiftKey?.05:.005;f.center[0]=Math.max(0,Math.min(1,f.center[0]+(event.key==='ArrowLeft'?-step:event.key==='ArrowRight'?step:0)));f.center[1]=Math.max(0,Math.min(1,f.center[1]+(event.key==='ArrowUp'?-step:event.key==='ArrowDown'?step:0)));state.framing.set(state.selectedFrame,f);loadFramingControls();});
  $('render-frame-preview').addEventListener('click',async()=>{const path=state.selectedFrame;if(!path){showError('Add a camera recording first.');return;}const button=$('render-frame-preview');button.disabled=true;button.textContent='Rendering…';try{const camera=state.cameras.find(c=>(state.files[c.key]||[]).includes(path));const result=await api('/api/preview',{path,angle:camera.id,mode:mode(),framing:frameFor(path),time:number('frame-time')});state.previewUrls={output:result.url};state.previewFiles={output:path};renderPreviews();setTab('framing');}catch(error){showError(error);}finally{button.disabled=false;button.textContent='Check output crop ↗';}});

  function selectPage(name){state.page=name;for(const page of ['edit','highlights','effects'])$(`${page}-page`).hidden=page!==name;$$('[data-page]').forEach(button=>button.setAttribute('aria-selected',String(button.dataset.page===name)));for(const w of Object.values(state.waves))w.draw();window.scrollTo({top:0,behavior:'smooth'});}
  $$('[data-page]').forEach(button=>button.addEventListener('click',()=>selectPage(button.dataset.page)));
  for(const target of ['highlight','effects','highlight-output','effects-output'])$(`browse-${target}`).addEventListener('click',()=>openBrowser(target));
  function setLatestSource(target){if(!state.latestEdit){showError('Render an edit first, or browse to an existing finished video.');return;}$(`${target}-source`).value=state.latestEdit;if(target==='highlight')loadHighlightWave();}
  $('highlight-use-edit').addEventListener('click',()=>setLatestSource('highlight'));$('effects-use-edit').addEventListener('click',()=>setLatestSource('effects'));

  function createWaveform(id,hostId){
    const host=$(hostId);host.replaceChildren();const empty=textEl('p','Load audio to inspect the waveform and choose a range.','help waveform-empty');host.append(empty);const body=textEl('div','','waveform-body');body.hidden=true;
    const scroll=textEl('div','','wave-scroll'),canvas=document.createElement('canvas');canvas.className='wave-canvas';canvas.tabIndex=0;canvas.setAttribute('aria-label','Audio waveform: click to seek or drag to select a range.');scroll.append(canvas);const ruler=textEl('div','','wave-ruler');const clock=textEl('span','00:00');ruler.append(clock);const zoomLabel=textEl('label','Zoom ');const zoom=document.createElement('select');for(const n of [1,2,4,8,16]){const option=textEl('option',`${n}×`);option.value=n;zoom.append(option);}zoomLabel.append(zoom);ruler.append(zoomLabel);const player=document.createElement('audio');player.controls=true;player.preload='metadata';const fields=textEl('div','','wave-selection');const startLabel=textEl('label','Selection start (seconds)'),start=document.createElement('input');start.type='number';start.min=0;start.step='.001';start.value=0;startLabel.append(start);const endLabel=textEl('label','Selection end (seconds)'),end=document.createElement('input');end.type='number';end.min=0;end.step='.001';end.value=0;endLabel.append(end);const play=textEl('button','Play selection','small');play.type='button';fields.append(startLabel,endLabel,play);body.append(scroll,ruler,player,fields);host.append(body);
    const w={duration:0,peaks:[],path:'',player,start,end,canvas,scroll,zoom,play,body,empty,selectionPlaying:false,
      selection(){return {start:Number(start.value),end:Number(end.value)};},
      setSelection(a,b){start.value=String(Math.max(0,Math.min(w.duration,a)));end.value=String(Math.max(0,Math.min(w.duration,b)));w.draw();},
      draw(){if(!w.duration)return;const cssWidth=Math.max(300,scroll.clientWidth||700)*Number(zoom.value);canvas.style.width=cssWidth+'px';canvas.style.height='135px';const dpr=window.devicePixelRatio||1;canvas.width=Math.round(cssWidth*dpr);canvas.height=Math.round(135*dpr);const ctx=canvas.getContext('2d');ctx.scale(dpr,dpr);ctx.fillStyle='#11170f';ctx.fillRect(0,0,cssWidth,135);const selection=w.selection();ctx.fillStyle='#c8df9330';ctx.fillRect(selection.start/w.duration*cssWidth,0,(selection.end-selection.start)/w.duration*cssWidth,135);ctx.strokeStyle='#91b7a0';ctx.lineWidth=1;const step=w.peaks.length/cssWidth;for(let x=0;x<cssWidth;x+=2){let value=0;const left=Math.floor(x*step),right=Math.min(w.peaks.length,Math.ceil((x+2)*step));for(let i=left;i<right;i++)value=Math.max(value,w.peaks[i]);ctx.beginPath();ctx.moveTo(x,67-value*55);ctx.lineTo(x,67+value*55);ctx.stroke();}ctx.strokeStyle='#e3edc2';for(const t of [selection.start,selection.end]){const x=t/w.duration*cssWidth;ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,135);ctx.stroke();}ctx.strokeStyle='#f0ae74';const position=player.currentTime/w.duration*cssWidth;ctx.beginPath();ctx.moveTo(position,0);ctx.lineTo(position,135);ctx.stroke();clock.textContent=`${timecode(player.currentTime)} / ${timecode(w.duration)} · ${(selection.end-selection.start).toFixed(2)}s selected`;},
      async load(path){empty.hidden=false;empty.textContent='Analysing audio… This can take a little while for a full set.';body.hidden=true;try{const response=await api('/api/waveform',{path});w.path=path;w.duration=response.duration;w.peaks=response.peaks;w.energetic=response.energetic||[];player.src=response.audio_url;start.max=end.max=w.duration;w.setSelection(0,Math.min(w.duration,30));empty.hidden=true;body.hidden=false;w.draw();return response;}catch(error){empty.textContent='Could not load this waveform.';throw error;}}
    };
    zoom.addEventListener('change',()=>w.draw());for(const input of [start,end])input.addEventListener('input',()=>w.draw());player.addEventListener('timeupdate',()=>{if(w.selectionPlaying&&player.currentTime>=Number(end.value)){player.pause();w.selectionPlaying=false;}w.draw();});player.addEventListener('pause',()=>{w.selectionPlaying=false;play.textContent='Play selection';});play.addEventListener('click',()=>{const range=w.selection();if(!w.duration||range.end<=range.start){showError('Choose a selection whose end is after its start.');return;}player.currentTime=range.start;w.selectionPlaying=true;player.play().catch(showError);play.textContent='Playing…';});
    let anchor=null,moved=false;const timeAt=event=>{const rect=canvas.getBoundingClientRect();return Math.max(0,Math.min(w.duration,(event.clientX-rect.left)/rect.width*w.duration));};canvas.addEventListener('pointerdown',event=>{if(!w.duration)return;canvas.setPointerCapture(event.pointerId);anchor=timeAt(event);moved=false;});canvas.addEventListener('pointermove',event=>{if(anchor===null)return;const t=timeAt(event);if(Math.abs(t-anchor)>.01){moved=true;w.setSelection(Math.min(anchor,t),Math.max(anchor,t));}});canvas.addEventListener('pointerup',event=>{if(anchor===null)return;if(!moved)player.currentTime=timeAt(event);anchor=null;w.draw();});canvas.addEventListener('pointercancel',()=>anchor=null);state.waves[id]=w;return w;
  }
  createWaveform('edit','edit-wave-host');createWaveform('highlight','highlight-wave-host');window.addEventListener('resize',()=>Object.values(state.waves).forEach(w=>w.draw()));
  $('load-edit-wave').addEventListener('click',async()=>{const path=state.files.audio[0];if(!path){showError('Choose an audio bounce first.');return;}const button=$('load-edit-wave');button.disabled=true;try{await state.waves.edit.load(path);}catch(error){showError(error);}finally{button.disabled=false;}});
  function selectedRange(w){if(!w.duration)throw new Error('Load the waveform and select a time range first.');const {start,end}=w.selection();if(!Number.isFinite(start)||!Number.isFinite(end)||start<0||end> w.duration+.001||end<=start)throw new Error('Choose a valid selection inside the source duration.');return {start,end};}
  $('add-shot-override').addEventListener('click',()=>{try{const range=selectedRange(state.waves.edit);if(state.waves.edit.path!==state.files.audio[0])throw new Error('Reload the waveform for the current audio bounce first.');if(state.shotOverrides.some(o=>range.start<o.end&&range.end>o.start))throw new Error('This selection overlaps an existing forced angle. Remove or adjust that range first.');const camera_id=$('override-camera').value;if(!camera_id)throw new Error('Add a camera first.');const entry={...range,camera_id};if($('override-part').value)entry.source_path=$('override-part').value;state.shotOverrides.push(entry);state.shotOverrides.sort((a,b)=>a.start-b.start);renderShotOverrides();toast('Camera override added to the edit.');}catch(error){showError(error);}});
  function renderShotOverrides(){const host=$('shot-overrides');host.replaceChildren();for(const [index,entry]of state.shotOverrides.entries()){const row=textEl('div','','override-row');row.append(textEl('span',`${timecode(entry.start)}–${timecode(entry.end)} · ${entry.camera_id} · ${entry.source_path?basename(entry.source_path):'Any available part'}`));const button=textEl('button','×','icon-button');button.type='button';button.setAttribute('aria-label','Remove forced angle');button.addEventListener('click',()=>{state.shotOverrides.splice(index,1);renderShotOverrides();});row.append(button);host.append(row);}}
  for(const [button,id]of [['mark-drop','drops'],['mark-breakdown','breakdowns']])$(button).addEventListener('click',()=>{try{const range=selectedRange(state.waves.edit);$(id).value+=($(id).value?'\n':'')+`${timecode(range.start,2)}–${timecode(range.end,2)}`;toast(`Selection added to ${id}.`);}catch(error){showError(error);}});
  async function loadHighlightWave(){const path=$('highlight-source').value.trim();if(!path){showError('Choose a finished movie first.');return;}const button=$('highlight-load');button.disabled=true;try{const response=await state.waves.highlight.load(path);renderEnergy(response.energetic||[]);}catch(error){showError(error);}finally{button.disabled=false;}}
  $('highlight-load').addEventListener('click',loadHighlightWave);
  function renderEnergy(suggestions){const host=$('energy-suggestions');host.replaceChildren();$('energy-count').textContent=`${suggestions.length} SUGGESTIONS`;if(!suggestions.length){host.append(textEl('p','No distinct energetic sections were detected. You can still select any range in the waveform.','help'));return;}suggestions.forEach((item,index)=>{const row=textEl('button','','energy-row');row.type='button';const label=textEl('span',String(index+1).padStart(2,'0'),'energy-number');const detail=textEl('span',`${timecode(item.start)}–${timecode(item.end)}`);detail.append(textEl('small',`${(item.end-item.start).toFixed(1)} seconds`));row.append(label,detail,textEl('span','Select →','energy-action'));row.addEventListener('click',()=>{state.waves.highlight.setSelection(item.start,item.end);state.waves.highlight.player.currentTime=item.start;$$('.energy-row').forEach(r=>r.classList.toggle('selected',r===row));});host.append(row);});}
  $('highlight-to-effects').addEventListener('click',()=>{try{const range=selectedRange(state.waves.highlight);if(state.waves.highlight.path!==$('highlight-source').value.trim())throw new Error('Load the waveform for the selected source movie first.');$('effects-source').value=state.waves.highlight.path;$('effects-start').value=range.start;$('effects-end').value=range.end;selectPage('effects');toast('Selection sent to Effects.');}catch(error){showError(error);}});
  $('export-highlight').addEventListener('click',()=>{try{const range=selectedRange(state.waves.highlight);if(state.waves.highlight.path!==$('highlight-source').value.trim())throw new Error('Load the waveform for the selected source movie first.');startToolJob('/api/clips',{source_path:state.waves.highlight.path,...range,output_dir:$('highlight-output').value.trim(),output_name:$('highlight-name').value.trim(),crf:number('crf'),preset:$('preset').value,overwrite:$('highlight-overwrite').checked},'clip');}catch(error){showError(error);}});
  for(const id of ['bounce','brightness','contrast','saturation'])$(`effects-${id}`).addEventListener('input',()=>{$(`effects-${id}-value`).textContent=id==='bounce'?`${Math.round(number('effects-'+id)*100)}%`:number('effects-'+id).toFixed(2);});
  function effectConfig(preview){return {source_path:$('effects-source').value.trim(),output_dir:$('effects-output').value.trim(),output_name:$('effects-name').value.trim(),start:number('effects-start'),end:$('effects-end').value===''?null:number('effects-end'),fade_in:number('effects-fade-in'),fade_out:number('effects-fade-out'),bounce:number('effects-bounce'),brightness:number('effects-brightness'),contrast:number('effects-contrast'),saturation:number('effects-saturation'),style:$('effects-style').value,vignette:$('effects-vignette').checked,overwrite:$('effects-overwrite').checked,crf:number('crf'),preset:$('preset').value,preview};}
  $('preview-effects').addEventListener('click',()=>startToolJob('/api/effects',effectConfig(true),'effects'));$('export-effects').addEventListener('click',()=>startToolJob('/api/effects',effectConfig(false),'effects'));
  async function startToolJob(endpoint,config,kind){if(state.busy||state.uploadBusy){toast('Wait for the current job or cancel it first.');return;}try{if(!config.source_path||!config.output_dir)throw new Error('Choose a source movie and an output folder.');state.activeKind=kind;state.busy=true;setJobButtons();$('error-banner').hidden=true;const result=await api(endpoint,config);state.jobId=result.id;state.reportKey='';state.lastLog='';pollJob();}catch(error){state.busy=false;setJobButtons();showError(error);}}
  function updateToolProgress(job){for(const host of $$('[data-tool-status]')){host.hidden=false;host.replaceChildren();const heading=textEl('div','','section-heading');heading.append(textEl('h2',`${job.kind==='clip'?'Highlight':job.kind==='effects'?'Effects':'Edit'} · ${job.status}`));if(['queued','running'].includes(job.status)){const cancel=textEl('button','Cancel','danger small');cancel.type='button';cancel.addEventListener('click',async()=>{cancel.disabled=true;try{await api(`/api/jobs/${encodeURIComponent(job.id)}/cancel`,{});pollJob();}catch(error){showError(error);}});heading.append(cancel);}host.append(heading,textEl('p',job.error||job.stage||'','help'));const logs=textEl('pre',(job.logs||[]).slice(-12).join('\n'),'tool-logs');host.append(logs);}}
  function renderToolResult(job){const effects=job.kind==='effects',host=$(effects?'effects-result':'highlight-result');host.hidden=false;host.replaceChildren();const report=job.report||{},video=(job.artifacts||[]).find(a=>a.kind==='video');host.append(textEl('h3',job.config?.preview?'Preview ready':'Export ready'));if(report.outputs?.video)host.append(textEl('p',report.outputs.video,'help result-path'));const downloads=textEl('div','','downloads');for(const artifact of job.artifacts||[]){const link=textEl('a',`↓ ${artifact.kind==='video'?'Download video':artifact.name}`);link.href=artifact.url;link.download=artifact.name;downloads.append(link);}host.append(downloads);if(video){if(effects){$('effects-video').src=video.url;$('effects-video').hidden=false;$('effects-empty').hidden=true;}else{const player=document.createElement('video');player.src=video.url;player.controls=true;player.preload='metadata';player.className='highlight-video';host.append(player);const send=textEl('button','Use this exported clip in Effects →','small');send.type='button';send.addEventListener('click',()=>{$('effects-source').value=report.outputs?.video||job.config?.output_path||'';$('effects-start').value=0;$('effects-end').value='';selectPage('effects');});host.append(send);}}}
  function renderTimelineKey(report){const host=document.querySelector('.timeline-key');host.replaceChildren();const shares=report.stats?.camera_shares||{};for(const camera of state.cameras){const label=textEl('span',''),swatch=document.createElement('i');swatch.style.background=cameraColor(camera.id);label.append(swatch,document.createTextNode(`${camera.id}${shares[camera.id]!=null?' '+Math.round(shares[camera.id]*100)+'%':''}`));host.append(label);}const black=textEl('span','No footage');black.id='black-key';black.hidden=true;const dot=document.createElement('i');dot.className='key-black';black.prepend(dot);host.append(black);const duration=textEl('span','');duration.id='timeline-duration';host.append(duration);}

  function dependencyAvailable(value){if(value===null||value===undefined||value===false)return false;if(typeof value==='object'){if('available' in value)return !!value.available;if('ok' in value)return !!value.ok;}return !!value;}
  async function fetchSetup(){const data=await api('/api/setup');setupState.data=data;state.config={...(state.config||{}),default_folder:data.default_folder,default_output:data.default_output,dependencies:data.dependencies,setup_completed:data.completed,can_render:data.can_render};return data;}
  async function openSetup(firstRun=false){setupState.loading=true;setupState.firstRun=firstRun;setupState.step=firstRun?0:1;$('setup-error').hidden=true;$('setup-save-status').textContent='';$('setup-title').textContent=firstRun?'Welcome to your studio.':'Studio settings';$('setup-description').textContent=firstRun?'A few quick choices, then you’re ready to start.':'Default folders, editing tools, and help when you need it.';if(!$('setup-dialog').open)$('setup-dialog').showModal();renderSetupStep();try{const data=await fetchSetup();$('setup-default-folder').value=data.default_folder||'';$('setup-default-output').value=data.default_output||'';renderRuntime(data);setJobButtons();}catch(error){setupError(error);}finally{setupState.loading=false;renderSetupStep();}}
  function setupError(error){$('setup-error').textContent=error.message||String(error);$('setup-error').hidden=false;}
  function renderSetupStep(){const step=setupState.step;$$('[data-setup-panel]').forEach(panel=>panel.hidden=Number(panel.dataset.setupPanel)!==step);$$('[data-setup-step]').forEach(item=>{const active=Number(item.dataset.setupStep)===step;item.classList.toggle('complete',Number(item.dataset.setupStep)<step);if(active)item.setAttribute('aria-current','step');else item.removeAttribute('aria-current');});$('setup-back').hidden=step===0;$('setup-next').textContent=['Get started','Save folders & check',setupState.data?.completed?'Continue':'Save folders','Open workspace'][step];$('setup-next').disabled=setupState.loading||setupState.saving||(step===2&&!setupState.data?.can_render);$('setup-back').disabled=setupState.loading||setupState.saving;if(step===3){$('ready-default-folder').textContent=setupState.data?.default_folder||$('setup-default-folder').value;$('ready-default-output').textContent=setupState.data?.default_output||$('setup-default-output').value;}}
  function renderRuntime(data){const host=$('runtime-checks');host.replaceChildren();const labels={ffmpeg:'Video rendering',ffprobe:'Media inspection',numpy:'Audio analysis',scipy:'Audio matching'};let allReady=true;for(const [key,label]of Object.entries(labels)){const value=data.dependencies?.[key],ok=dependencyAvailable(value);allReady=allReady&&ok;const row=textEl('div','','runtime-row');row.dataset.ready=String(ok);const icon=textEl('span',ok?'✓':'!','runtime-icon');icon.setAttribute('aria-hidden','true');const name=textEl('div',label);name.append(textEl('small',key==='ffmpeg'?'Encode your final video':key==='ffprobe'?'Read recording formats and timing':key==='numpy'?'Compare camera and master audio':'Find offsets and clock drift'));row.append(icon,name,textEl('span',ok?'Ready':'Unavailable','runtime-result'));host.append(row);}const ready=typeof data.can_render==='boolean'?data.can_render:allReady;setupState.data={...data,can_render:ready};$('runtime-summary').textContent=ready?'Everything needed to process your recordings is available.':'Some editing tools are unavailable. Your files and settings are safe.';$('runtime-help').hidden=ready;$('dependency-warning').hidden=ready;if(!ready)$('dependency-warning').textContent='Some editing tools are unavailable. Open Settings to check the app before rendering.';setJobButtons();const arch=data.architecture==='arm64'?'Apple silicon':data.architecture==='x86_64'?'Intel':data.architecture||'';$('runtime-machine').textContent=[data.version?`Multicam Studio ${data.version}`:'',data.platform==='Darwin'?'macOS':data.platform||'',arch].filter(Boolean).join(' · ');renderSetupStep();}
  $('open-preferences').addEventListener('click',()=>openSetup(false));$('setup-close').addEventListener('click',()=>$('setup-dialog').close());$('setup-back').addEventListener('click',()=>{setupState.step=Math.max(0,setupState.step-1);$('setup-error').hidden=true;renderSetupStep();});
  $('setup-next').addEventListener('click',async()=>{if(setupState.loading||setupState.saving)return;const step=setupState.step;$('setup-error').hidden=true;if(step===0){setupState.step=1;renderSetupStep();$('setup-default-folder').focus();return;}if(step===3){$('setup-dialog').close();toast('Studio preferences saved. Add your recordings to start.');return;}if(step===2){if(setupState.data?.can_render){setupState.step=setupState.data.completed?3:1;renderSetupStep();}return;}const default_folder=$('setup-default-folder').value.trim(),default_output=$('setup-default-output').value.trim();if(!default_folder||!default_output){setupError('Choose both a recordings folder and an export folder.');return;}setupState.saving=true;$('setup-save-status').textContent='Checking folders…';renderSetupStep();try{const oldOutput=state.config?.default_output;await api('/api/setup',{default_folder,default_output});const data=await fetchSetup();for(const id of ['output-dir','highlight-output','effects-output'])if(!$(id).value||$(id).value===oldOutput)$(id).value=data.default_output;$('setup-save-status').textContent='Preferences saved.';setupState.step=2;renderRuntime(data);scheduleAutosave();}catch(error){setupError(error);$('setup-save-status').textContent='';if(setupState.data?.can_render===false){setupState.step=2;renderRuntime(setupState.data);}}finally{setupState.saving=false;renderSetupStep();}});
  $('recheck-runtime').addEventListener('click',async()=>{const button=$('recheck-runtime');button.disabled=true;$('runtime-summary').textContent='Checking the editing tools…';try{renderRuntime(await fetchSetup());$('setup-error').hidden=true;}catch(error){setupError(error);}finally{button.disabled=false;}});
  $('browse-setup-folder').addEventListener('click',()=>openBrowser('setup-default-folder'));$('browse-setup-output').addEventListener('click',()=>openBrowser('setup-default-output'));
  $('download-diagnostics').addEventListener('click',async()=>{const button=$('download-diagnostics');button.disabled=true;$('diagnostics-status').textContent=' Preparing report…';try{const response=await fetch('/api/diagnostics',{headers:{'X-Multicam-Token':window.MULTICAM_TOKEN}});if(!response.ok){let data;try{data=await response.json();}catch{}throw new Error(data?.error||'Could not prepare the diagnostic report. Please try again.');}const blob=await response.blob(),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download='multicam-diagnostics.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);$('diagnostics-status').textContent=' Report downloaded.';}catch(error){$('diagnostics-status').textContent='';setupError(error);}finally{button.disabled=false;}});

  $('new-folder-button').addEventListener('click',()=>{$('new-folder-form').hidden=false;$('new-folder-name').value='';$('new-folder-name').focus();});$('cancel-folder-button').addEventListener('click',()=>{$('new-folder-form').hidden=true;});
  $('new-folder-form').addEventListener('submit',async event=>{event.preventDefault();const name=$('new-folder-name').value.trim();if(!name||name==='.'||name==='..'||/[\\/\x00]/.test(name)){$('browser-error').textContent='Enter a folder name without slashes.';$('browser-error').hidden=false;return;}const button=$('create-folder-button');button.disabled=true;try{const result=await api('/api/folders',{parent:state.browser.path,name});$('new-folder-form').hidden=true;await browse(result.path||`${state.browser.path.replace(/\/$/,'')}/${name}`);}catch(error){$('browser-error').textContent=error.message;$('browser-error').hidden=false;}finally{button.disabled=false;}});

  $('quit-studio').addEventListener('click',async()=>{const button=$('quit-studio');button.disabled=true;button.textContent='Closing studio…';try{saveLocalDraft();await api('/api/shutdown',{});setupState.stopped=true;clearTimeout(state.pollTimer);for(const media of $$('audio,video'))media.pause();for(const child of [...$('setup-dialog').children])child.hidden=child.id!=='shutdown-message';$('setup-dialog').setAttribute('aria-labelledby','shutdown-message');$('setup-dialog').removeAttribute('aria-describedby');}catch(error){setupError(error);button.disabled=false;button.textContent='Quit Multicam Studio';}});$('setup-dialog').addEventListener('cancel',event=>{if(setupState.stopped)event.preventDefault();});

  const autosaveToolIds=['highlight-source','highlight-output','highlight-name','highlight-overwrite','effects-source','effects-start','effects-end','effects-output','effects-name','effects-style','effects-fade-in','effects-fade-out','effects-bounce','effects-brightness','effects-contrast','effects-saturation','effects-vignette','effects-overwrite'];
  function toolDraft(){const tools={};for(const id of autosaveToolIds){const input=$(id);tools[id]=input.type==='checkbox'?input.checked:input.value;}return tools;}
  function scheduleAutosave(){if(!draftState.ready||draftState.offered)return;clearTimeout(draftState.timer);draftState.timer=setTimeout(saveLocalDraft,700);}
  function saveLocalDraft(){if(!draftState.ready||draftState.offered)return;try{const project=collectConfig(false,false);if(!project.cameras.some(c=>c.clips?.length)&&!project.audio)return;const tools=toolDraft(),signature=JSON.stringify({project,tools});if(signature===draftState.signature)return;localStorage.setItem(draftState.key,JSON.stringify({schema:1,saved_at:new Date().toISOString(),project,tools}));draftState.signature=signature;$('autosave-status').textContent=`Draft saved in this browser · ${new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}`;}catch(error){if(error.name==='QuotaExceededError'||error.name==='SecurityError'){draftState.ready=false;$('autosave-status').textContent='Local draft storage unavailable. Use Save project to keep a copy.';toast('Local draft storage is unavailable. Use Save project to keep a copy.');}}}
  function offerLocalDraft(){try{const raw=localStorage.getItem(draftState.key);if(!raw)return;const draft=JSON.parse(raw);if(draft?.schema!==1||!draft.project||!Array.isArray(draft.project.cameras))return;if(!draft.project.cameras.some(c=>Array.isArray(c.clips)&&c.clips.length)&&!draft.project.audio)return;draftState.offered=draft;const date=new Date(draft.saved_at);$('draft-description').textContent=`Saved ${Number.isNaN(date.getTime())?'in this browser':date.toLocaleString()} · File paths and settings only; recordings stay in place.`;$('draft-banner').hidden=false;$('autosave-status').textContent='Restore or discard the saved draft to resume automatic saving.';}catch{/* Storage can be unavailable in a private browser window. */}}
  $('restore-draft').addEventListener('click',()=>{const draft=draftState.offered;if(!draft)return;try{applyConfig(draft.project);for(const id of autosaveToolIds){if(draft.tools?.[id]===undefined)continue;const input=$(id);if(input.type==='checkbox')input.checked=!!draft.tools[id];else input.value=draft.tools[id];if(input.type==='range')input.dispatchEvent(new Event('input',{bubbles:true}));}draftState.signature=JSON.stringify({project:draft.project,tools:draft.tools||{}});draftState.offered=null;$('draft-banner').hidden=true;$('autosave-status').textContent='Draft restored. Changes are saved automatically in this browser.';toast('Draft restored. Check that your recording drives are connected.');scheduleAutosave();}catch(error){showError(error);}});
  $('discard-draft').addEventListener('click',()=>{try{localStorage.removeItem(draftState.key);}catch{}draftState.offered=null;draftState.signature='';$('draft-banner').hidden=true;$('autosave-status').textContent='Local drafts remember your file paths and settings.';scheduleAutosave();});
  document.addEventListener('input',scheduleAutosave);document.addEventListener('change',scheduleAutosave);document.addEventListener('click',scheduleAutosave);document.addEventListener('pointerup',scheduleAutosave);window.addEventListener('pagehide',saveLocalDraft);

  initialize();
})();
